// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBpREmtb5vjhGBkp-Yzu_v9nba-kiOf8go',
    appId: '1:587281289420:web:92b1063e58f04e39dbf269',
    messagingSenderId: '587281289420',
    projectId: 'ganagov-34322',
    authDomain: 'ganagov-34322.firebaseapp.com',
    storageBucket: 'ganagov-34322.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4nnszdAmab33Wlof8HMKrcYa7ONDDkcs',
    appId: '1:587281289420:android:238583de3b93b67ddbf269',
    messagingSenderId: '587281289420',
    projectId: 'ganagov-34322',
    storageBucket: 'ganagov-34322.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhtvxo_Eh-M-gS20arwg1oMqHsFnuWaMY',
    appId: '1:587281289420:ios:95b892e819533a35dbf269',
    messagingSenderId: '587281289420',
    projectId: 'ganagov-34322',
    storageBucket: 'ganagov-34322.appspot.com',
    iosBundleId: 'com.example.ganagov',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDhtvxo_Eh-M-gS20arwg1oMqHsFnuWaMY',
    appId: '1:587281289420:ios:95b892e819533a35dbf269',
    messagingSenderId: '587281289420',
    projectId: 'ganagov-34322',
    storageBucket: 'ganagov-34322.appspot.com',
    iosBundleId: 'com.example.ganagov',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBpREmtb5vjhGBkp-Yzu_v9nba-kiOf8go',
    appId: '1:587281289420:web:d44de09f3e92e841dbf269',
    messagingSenderId: '587281289420',
    projectId: 'ganagov-34322',
    authDomain: 'ganagov-34322.firebaseapp.com',
    storageBucket: 'ganagov-34322.appspot.com',
  );
}
